# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simple matrix multiplication
#'
#' @param ef Matrix
#' @param L Matrix
#' @param FD Matrix
#'
#' @return Product of matrices
#' @export
#'
#' @importFrom Rcpp evalCpp
#'
#' @examples
#' A <- matrix(1:9, 3, 3)
#' B <- matrix(11:19, 3, 3)
#' C <- matrix(4:12, 3, 3)
#' CFPcalculationRCPP(A, B, C)
CFPcalculationRCPP <- function(ef, L, FD) {
    .Call(`_AnalyseMRIO_CFPcalculationRCPP`, ef, L, FD)
}

#' Simple matrix multiplication
#'
#' @param matA Matrix
#' @param matB Matrix
#'
#' @return Product of matrices
#' @export
#'
#' @importFrom Rcpp evalCpp
#'
#' @examples
#' A <- matrix(1:9, 3, 3)
#' B <- matrix(11:19, 3, 3)
#' Mult2_rcpp3(A, B)
Mult2_rcpp3 <- function(matA, matB) {
    .Call(`_AnalyseMRIO_Mult2_rcpp3`, matA, matB)
}

#' Inversion de matrice
#'
#' @param m1 Matrix
#'
#' @return Inverse de la matrice
#' @export
#'
#' @importFrom Rcpp evalCpp
#'
#' @examples
#' A <- diag(2,3)
#' inversion_rcpp3(A)
inversion_rcpp3 <- function(m1) {
    .Call(`_AnalyseMRIO_inversion_rcpp3`, m1)
}

